"""create_insights_tables

Revision ID: 7da1ec7101f8
Revises: e5f66682f6dc
Create Date: 2026-07-22 03:20:04.626916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da1ec7101f8'
down_revision: Union[str, None] = 'e5f66682f6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_health_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_cash_flow', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('savings_rate', sa.Float(), nullable=False),
    sa.Column('essential_expenses', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discretionary_expenses', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('largest_category', sa.String(length=100), nullable=True),
    sa.Column('largest_merchant', sa.String(length=100), nullable=True),
    sa.Column('financial_health_score', sa.Integer(), nullable=False),
    sa.Column('score_version', sa.String(length=20), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_health_snapshots_user_id'), 'financial_health_snapshots', ['user_id'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_fingerprint'), 'insights', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_insights_user_id'), 'insights', ['user_id'], unique=False)
    op.create_table('recurring_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('average_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('next_expected_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_transaction_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_payments_user_id'), 'recurring_payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_payments_user_id'), table_name='recurring_payments')
    op.drop_table('recurring_payments')
    op.drop_index(op.f('ix_insights_user_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_fingerprint'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_financial_health_snapshots_user_id'), table_name='financial_health_snapshots')
    op.drop_table('financial_health_snapshots')
    # ### end Alembic commands ###
