"""create_transactions_and_raw_tables

Revision ID: 86d4f7d8a21d
Revises: 2a171978fc60
Create Date: 2026-07-22 02:27:41.323507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d4f7d8a21d'
down_revision: Union[str, None] = '2a171978fc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alter the Enum values in Postgres
    op.execute("COMMIT")
    op.execute("ALTER TYPE upload_status_enum ADD VALUE 'QUEUED'")
    op.execute("ALTER TYPE upload_status_enum ADD VALUE 'PARSING'")
    op.execute("ALTER TYPE upload_status_enum ADD VALUE 'NORMALIZING'")
    op.execute("ALTER TYPE upload_status_enum ADD VALUE 'COMPLETED'")
    op.execute("ALTER TYPE upload_status_enum ADD VALUE 'COMPLETED_WITH_WARNINGS'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('parser_name', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_transactions_statement_id'), 'raw_transactions', ['statement_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_fingerprint'), 'transactions', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.add_column('statements', sa.Column('parsing_duration_ms', sa.Integer(), nullable=True))
    op.add_column('statements', sa.Column('parser_errors', sa.String(), nullable=True))
    op.add_column('statements', sa.Column('warnings_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'warnings_count')
    op.drop_column('statements', 'parser_errors')
    op.drop_column('statements', 'parsing_duration_ms')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_statement_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_fingerprint'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_raw_transactions_statement_id'), table_name='raw_transactions')
    op.drop_table('raw_transactions')
    # ### end Alembic commands ###
