"""create_intelligence_tables

Revision ID: e5f66682f6dc
Revises: 86d4f7d8a21d
Create Date: 2026-07-22 02:55:18.136687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f66682f6dc'
down_revision: Union[str, None] = '86d4f7d8a21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('categorization_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorization_rules_pattern'), 'categorization_rules', ['pattern'], unique=True)
    op.create_index(op.f('ix_categorization_rules_priority'), 'categorization_rules', ['priority'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('merchant_type', sa.String(length=50), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('preferred_category_id', sa.UUID(), nullable=True),
    sa.Column('average_transaction_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preferred_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_canonical_name'), 'merchants', ['canonical_name'], unique=True)
    op.create_table('categorization_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('original_category_id', sa.UUID(), nullable=True),
    sa.Column('suggested_category_id', sa.UUID(), nullable=True),
    sa.Column('final_category_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence_reasons', sa.JSON(), nullable=True),
    sa.Column('correction_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_confidence', sa.Float(), nullable=True),
    sa.Column('correction_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['final_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorization_histories_transaction_id'), 'categorization_histories', ['transaction_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'merchants', ['merchant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_categorization_histories_transaction_id'), table_name='categorization_histories')
    op.drop_table('categorization_histories')
    op.drop_index(op.f('ix_merchants_canonical_name'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_categorization_rules_priority'), table_name='categorization_rules')
    op.drop_index(op.f('ix_categorization_rules_pattern'), table_name='categorization_rules')
    op.drop_table('categorization_rules')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
