import os
import time
import httpx
from typing import List, Tuple, Dict, Any
from app.conversation.services.llm_provider import LLMProvider

class GeminiProvider(LLMProvider):
    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY")
        self.model_name = "gemini-1.5-flash"

    async def generate_response(
        self,
        system_prompt: str,
        user_message: str,
        chat_history: List[dict]
    ) -> Tuple[str, Dict[str, Any]]:
        start_time = time.perf_counter()

        if not self.api_key:
            return self._generate_mock_fallback(system_prompt, user_message, chat_history, start_time)

        contents = []
        for msg in chat_history:
            role = "user" if msg["sender"] == "USER" else "model"
            contents.append({
                "role": role,
                "parts": [{"text": msg["content"]}]
            })

        contents.append({
            "role": "user",
            "parts": [{"text": user_message}]
        })

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model_name}:generateContent?key={self.api_key}"
        payload = {
            "contents": contents,
            "systemInstruction": {
                "parts": [{"text": system_prompt}]
            },
            "generationConfig": {
                "temperature": 0.2,
                "maxOutputTokens": 1000
            }
        }

        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(url, json=payload, timeout=20.0)
                if response.status_code != 200:
                    return f"Error from Gemini API: {response.text}", {
                        "model_used": self.model_name,
                        "token_usage": {"prompt_tokens": 0, "completion_tokens": 0},
                        "latency_ms": int((time.perf_counter() - start_time) * 1000)
                    }

                data = response.json()
                candidates = data.get("candidates", [])
                response_text = "No response generated by Gemini."
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts:
                        response_text = parts[0].get("text", "")

                usage_metadata = data.get("usageMetadata", {})
                prompt_tokens = usage_metadata.get("promptTokenCount", 0)
                completion_tokens = usage_metadata.get("candidatesTokenCount", 0)

                latency = int((time.perf_counter() - start_time) * 1000)
                return response_text, {
                    "model_used": self.model_name,
                    "token_usage": {
                        "prompt_tokens": prompt_tokens,
                        "completion_tokens": completion_tokens
                    },
                    "latency_ms": latency
                }

        except Exception as e:
            return f"Gemini connection failed: {str(e)}", {
                "model_used": self.model_name,
                "token_usage": {"prompt_tokens": 0, "completion_tokens": 0},
                "latency_ms": int((time.perf_counter() - start_time) * 1000)
            }

    def _generate_mock_fallback(
        self,
        system_prompt: str,
        user_message: str,
        chat_history: List[dict],
        start_time: float
    ) -> Tuple[str, Dict[str, Any]]:
        query = user_message.lower().strip()

        if "broke" in query or "salary" in query or "go" in query:
            import re
            income_match = re.search(r"Total Monthly Income: NGN ([0-9,.]+)", system_prompt)
            expenses_match = re.search(r"Total Monthly Expenses: NGN ([0-9,.]+)", system_prompt)
            inc = income_match.group(1) if income_match else "300000.00"
            exp = expenses_match.group(1) if expenses_match else "44,500.00"
            response_text = (
                f"Your monthly income is NGN {inc}, while your expenses stand at NGN {exp}. "
                "Let's look at where that spending went to make sure you have enough before payday!"
            )
        elif "subscription" in query or "netflix" in query:
            if "Netflix Subscription" in system_prompt or "netflix" in system_prompt:
                response_text = (
                    "I detected an active Netflix Subscription of NGN 4,500.00. "
                    "If you are not using it regularly, canceling it could save you NGN 54,000.00 annually."
                )
            else:
                response_text = "I do not see any active subscriptions registered in your recent statements."
        elif "shoprite" in query or "groceries" in query:
            if "SHOPRITE" in system_prompt or "Shoprite" in system_prompt:
                response_text = (
                    "Your groceries spending includes POS SHOPRITE LEKKI. "
                    "This is one of your top discretionary categories, so we should keep an eye on duplicate grocery transactions."
                )
            else:
                response_text = "I do not see any grocery transactions registered in your recent statements."
        else:
            response_text = (
                "Hello! I am NairaLens AI, your personal financial coach. "
                "I can analyze your spending trends, recurring bills, and explain how to improve your financial score. "
                "What would you like to discuss today?"
            )

        latency = int((time.perf_counter() - start_time) * 1000)
        return response_text, {
            "model_used": "mock-gemini-1.5-flash",
            "token_usage": {
                "prompt_tokens": len(system_prompt.split()) + len(user_message.split()),
                "completion_tokens": len(response_text.split())
            },
            "latency_ms": latency
        }
